{"name": "test_create_double_user_return_status_code_403", "status": "passed", "description": "Проверка невозможности создании пользователя, когда он уже зарегистрирован.Получаем ошибку 403", "steps": [{"name": "Создание нового пользователя в системе", "status": "passed", "parameters": [{"name": "payload", "value": "{'email': 'firskulakov@example.org', 'password': '(%Do70nHh8', 'name': 'Панфил Фокич Баранов'}"}], "start": 1717267066828, "stop": 1717267067022}], "start": 1717267066828, "stop": 1717267067023, "uuid": "ed2afbcb-ba61-46c7-8368-e10a9eab452c", "historyId": "121f443b42b2d6885bb4e284f49440b5", "testCaseId": "121f443b42b2d6885bb4e284f49440b5", "fullName": "tests.test_create_user.TestCreateUser#test_create_double_user_return_status_code_403", "labels": [{"name": "story", "value": "Ручка /api/auth/register"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "WIN-BHU1OVNKOHE"}, {"name": "thread", "value": "13424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}